version: '3.8'
services:
  django:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DEV_ALLOWED_HOST: ${DEV_ALLOWED_HOST}
      PROD_ALLOWED_HOST: ${PROD_ALLOWED_HOST}
      DEV_ALLOWED_ORIGIN: ${DEV_ALLOWED_ORIGIN}
      PROD_ALLOWED_ORIGIN: ${PROD_ALLOWED_ORIGIN}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
    command: >
      sh -c " python manage.py wait_for_db && python manage.py makemigrations &&   python manage.py migrate &&  gunicorn backend.wsgi:application 0.0.0.0:8000"
  front:
    build: ./frontend
    depends_on:
      - django
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
